name: Tests
on:
  pull_request:
    branches: [ main ]
jobs:
  pg_tap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install deps
        run: npm i
      - name: Supabase Start
        working-directory: ./packages/enterprise-supabase
        run: npx supabase start
      - name: Run Tests
        working-directory: ./packages/enterprise-supabase
        run: npx supabase db test
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install deps
        run: npm i
      - name: Check Formatting
        run: npm run format:check
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install deps
        run: npm i
      - name: Check Formatting
        run: npm run lint